### ISSUE TITLE
Objective of these - Improvements

### ISSUE THREAD

**Issue by Marlysson** [thgcode/configurerclass#1]
Which objective this project?
Create a classes based in configurations?

I should like of contribute..

**Comment by thgcode** [comment]
The objective of the mixin is to set the attributes of an instantiated class
based on a configuration file.
For example, if you have a configuration file like this:

[server]
host = localhost
port = 4000
debug = no

Using this class, you can make a server class and when you load the
configuration file, the values will be set on the instance and be of the correct type.

class Server(Configurer):
    def __init__(self):
        self.load("server.conf", "server", ["port"], ["host"], ["debug"])

In this example, when you instantiate this class, host will be a string,
port an integer and debug a boolean.
You can access these atributes directly in the class, like so:
    def connect(self):
        if self.host:
            # Code for connecting goes here

Let me know if you need more clarification on something and I will try
to explain it.

**Comment by Marlysson** [comment]
Ahhh , great! Now I understood . Good feature.

Can I suggest some improvements ? That you will analyse whether this make sense , sure.

- Could remove the name of parameters [server] , this could be name of class that your attributes will came above , by example:

[**server**] ->name of class , and your attributes above
host = localhost
port = 4000
debug = no

And this way would like remove the next parameters after file name , so:

```python
def init(self):
    self.load("server.conf")

>>> self.load
'localhost'
```

```python
class Server(Configurer):
    def init(self):
        self.load("server.conf")
```

Or have some class variable especifily the file name attributes, some this:

```python
class Server(Configurer):

    file_attributes = 'path_to_file.ini'

    def init(self):
        pass
       # He the Configurer would load the class variable , but don't think as make this :smile: , but will be a good feature.
```

And the finally seems like this:

```python
class Server(Configurer):
    file_attributes = 'path_to_file.ini'

>> a = Server()
>> a.host
'localhost'
```

Some thoughts :smile:

**Comment by thgcode** [comment]
I have implemented some of your suggestions.
Now the example became:
server.conf:

[Server]
host = localhost
port = 4000
debug = no

server.py:
from configurer import Configurer

class Server(Configurer):
    def __init__(self):
        self.load("server.conf")

The section name needed to become capital because the class name was
capitalized.

**Comment by Marlysson** [comment]
Awesome !!!

Are you already was use ```namedtuple```?

I'm thinking how handle capitalization ..

**Comment by thgcode** [comment]
I used the getattr and setattr functions to change the class.
